### ISSUE TITLE
P13_Relevamiento del Proceso_kmlopez

### ISSUE THREAD

**Issue by apandradech** [kmlopez/rpa-interseguros#150]
| Item  | Detalle |
| ------------- | ------------- |
| Descripción de la tarea  | Relevamiento de información con key users |
| Persona de Contacto  | PO = Lourdes Huallaca<br/>KU = Karen Vidal
| Notas  |  |
| Link relacionado (Box)  | [https://ibm.ent.box.com/folder/82575905432](url) |
| Criterios de aceptación  | Todas las secciones del documento concluídas, Validación y aprobación de Lourdes Huallaca, Karen Vidal y @fechavez |

**Comment by kmlopez** [comment]
06/08 :  Se asigna a @kmlopez el proceso
Se coordina con con Karen Vidal pero indica que aplicación en la que se corre el proceso está generando errores por lo que se pospone para el 07/08.

**Comment by kmlopez** [comment]
07/08: Se hace seguimiento al issue con la aplicación. Lourdes indica que continúa con problemas.

**Comment by kmlopez** [comment]
09/08: Se realiza relevamiento teórico de proceso. Pendiente revisión del 50% restante por error de su sistema

**Comment by kmlopez** [comment]
14/08: Se completa relevamiento con Alejandra Arévalo
