### ISSUE TITLE
P13_Preparación del PDD_kmlopez

### ISSUE THREAD

**Issue by apandradech** [kmlopez/rpa-interseguros#152]
| Item  | Detalle |
| ------------- | ------------- |
| Descripción de la tarea  | Relevamiento de información con key users |
| Persona de Contacto  | PO = Lourdes Huallaca<br/>KU = Karen Vidal
| Notas  |  |
| Link relacionado (Box)  | https://ibm.ent.box.com/folder/82576898417 |
| Criterios de aceptación  | Todas las secciones del documento concluídas, Validación y aprobación de Lourdes Huallaca, Karen Vidal y @fechavez |

**Comment by kmlopez** [comment]
09/08 : Se avanza con la información que se cuenta al momento

**Comment by kmlopez** [comment]
12/08: key user indica que sistema aun sigue con error. Se espera correcto funcionamiento para mañana

**Comment by kmlopez** [comment]
15/08: Se termina PDD y se envía al cliente

**Comment by kmlopez** [comment]
19/08: Se recibe aceptación del cliente del documento:

![image](https://user-images.githubusercontent.com/26979268/63304952-9b76e500-c2aa-11e9-8c8b-27282f1091c8.png)
