### ISSUE TITLE
P14_Preparación del PDD_kmlopez

### ISSUE THREAD

**Issue by apandradech** [kmlopez/rpa-interseguros#154]
| Item  | Detalle |
| ------------- | ------------- |
| Descripción de la tarea  | Generación del PDD  |
| Persona de Contacto  | PO = Lourdes Huallaca<br/>KU= Karen Vidal<br/>KU = Sheley Chilón
| Notas  | --- |
| Link relacionado (Box)  | https://ibm.ent.box.com/folder/82573950189 |
| Criterios de aceptación  | Todas las secciones del documento concluídas, Validación y aprobación de Lourdes Huallaca, Sheley Chilón y @fechavez |

**Comment by kmlopez** [comment]
8/08 : Se genera PDD, se completa flujos y cuadros, pendiente terminar con detalle del proceso

**Comment by kmlopez** [comment]
09/08: Se entrega PDD para revisión, quedo a la esperas de las observaciones

**Comment by kmlopez** [comment]
12/08: Enviado a usuario para revisión. A la espera de observaciones.

**Comment by kmlopez** [comment]
19/08 : Se recibe aprobación de PO del documento:

![image](https://user-images.githubusercontent.com/26979268/63306099-dd098f00-c2ae-11e9-9f5c-eaa8df509cba.png)
