### ISSUE TITLE
P14_Definición del SDD_kmlopez

### ISSUE THREAD

**Issue by apandradech** [kmlopez/rpa-interseguros#155]
| Item  | Detalle |
| ------------- | ------------- |
| Descripción de la tarea  | Definición del SDD, desarrollo del documento |
| Persona de Contacto  | PO = Lourdes Huallaca<br/>KU = Sheley Chilón
| Notas  | --- |
| Link relacionado (Box)  | https://ibm.ent.box.com/folder/82573948989 |
| Criterios de aceptación  | Todas las secciones del documento concluídas, Validación y aprobación de Lourdes Huallaca, Sheley Chilón y @fechavez |

**Comment by kmlopez** [comment]
09/08 : Se inicia con la generación del SDD

**Comment by kmlopez** [comment]
14/08: Se envia SDD a cliente

**Comment by kmlopez** [comment]
19/08: Documento es aprobado por Lourdes Huallanca:

![image](https://user-images.githubusercontent.com/26979268/63305113-3a9bdc80-c2ab-11e9-9b28-42dbbbca73ab.png)
