### ISSUE TITLE
P12_Relevamiento del Proceso_kmlopez_tluna

### ISSUE THREAD

**Issue by apandradech** [kmlopez/rpa-interseguros#172]
| Item  | Detalle |
| ------------- | ------------- |
| Descripción de la tarea  | Relevamiento de información con key users |
| Persona de Contacto  | PO = Lourdes Huallaca<br/>KU = Sheley Chilón
| Notas  |  |
| Link relacionado (Box)  | [https://ibm.ent.box.com/folder/82575217298](url) |
| Criterios de aceptación  | Todas las secciones del documento concluídas, Validación y aprobación de Lourdes Huallaca, Karen Vidal y @fechavez |

**Comment by kmlopez** [comment]
06/08 se coordina reunión con key user para mañana en la tarde

**Comment by kmlopez** [comment]
07/08: Se realiza relevamiento de información

**Comment by kmlopez** [comment]
Se completa relevamiento
