### ISSUE TITLE
P12_Preparación del PDD_kmlopez_tluna

### ISSUE THREAD

**Issue by apandradech** [kmlopez/rpa-interseguros#173]
| Item  | Detalle |
| ------------- | ------------- |
| Descripción de la tarea  | Relevamiento de información con key users |
| Persona de Contacto  | PO = Lourdes Huallaca<br/>KU = Sheley Chilón
| Notas  | --- |
| Link relacionado (Box)  | https://ibm.ent.box.com/folder/82576866641 |
| Criterios de aceptación  | Todas las secciones del documento concluídas, Validación y aprobación de Lourdes Huallaca, Sheley Chilón y @fechavez |

**Comment by kmlopez** [comment]
Se tiene grafico y cuadros listos. pendiente culminar con el detalle del proceso.

**Comment by kmlopez** [comment]
08/08 : Se inicia preparación de PDD
09/08: Se envía a revisión

**Comment by kmlopez** [comment]
12/08: Enviado a usuario para revisión

**Comment by kmlopez** [comment]
19/08: Aprobado por PO 

![image](https://user-images.githubusercontent.com/26979268/63306626-03302e80-c2b1-11e9-8942-13604c4df3a3.png)
