### ISSUE TITLE
Validación de Acceso VPN

### ISSUE THREAD

**Issue by kmlopez** [kmlopez/rpa-interseguros#22]

**Comment by ManuelMayta** [comment]
Se realizo la validación de los accesos a los siguientes aplicativos con la VPN:
**Sistemas en el ambiente Preproduccion:**
     Acsele: http://10.23.103.22:7001/WController ----- OK
     Samp: http://10.23.103.13/samp ----- OK
     Conviweb: http://10.23.103.109/ConviWeb ----- OK
**Observaciones** 
Se necesita maquina virtual para ingresar al CRM, se envio correo a Christian Diaz de interseguro con copia a Sylvia , Frank, Eduardo y Pamela.
CRM: https://10.23.103.25/ISCRM ----- Pendiente

**Comment by ManuelMayta** [comment]
Los siguientes accesos estan pendiente:
     - AS - SURA
     - Web Viajes
     - SBS
     - Satélite
     - Workflow Hipotecario
     - Aplicativo Suiza LAB
     - SOLEM
     - INTERBANK,BCP,BBVA,SCOTIABANK
     - Aplicativo WinSCP
     - AMEX,MASTERCAD,VISA
     - Portal Qualitat

**Comment by ManuelMayta** [comment]
- Revisión del acceso a la VPN de Interseguro.
- Ingreso a la maquina virtual para el desarrollo de los bots.
- Acceso denegado en el Clienta de Automation Anywhere.

**Comment by ManuelMayta** [comment]
- Se valida el ingreso a la VPN de Interseguro para ingresar a  las VM.
- Se valida el ingreso a la VM de interseguro pero no se cuenta con internet.
- Se valida la instalación e ingreso al AA Client.
@fechavez  @ealburqu

**Comment by kmlopez** [comment]
Acceso correcto. Se cierra tarea
