### ISSUE TITLE
Tramas de Recaudación - Recaudación Individual

### ISSUE THREAD

**Issue by kmlopez** [kmlopez/rpa-interseguros#29]

**Comment by tanyaluna** [comment]
Necesidades:
*Acceso a las credenciales del correo
*Acceso a la web SAMP

1. Se ingresará al correo con las credenciales brindadas

2. Buscar el correo con el remitente y asunto para poder obtener la tabla de registros y las imágenes de los abonos a conciliar.

3. Se ingresará a la web SAMP con las credenciales brindadas.

4. Ingresar cada línea de registro seleccionando la cuenta según la moneda

5. Se debe seleccionar primer el abono y luego seleccionar la recaudación hasta llegar al monto del abono y se realiza la conciliación.

6. En los archivos Excel se debe completar la fecha y el número de conciliación.

Preguntas/Dudas:
Indicar o especificar los datos del correo (remitente, nombre del correo/asunto, nombre del archivo, etc)
La tabla indicada, ¿se encuentra en un archivo para descargar? o ¿se deberá leer desde el mismo correo?
Explicar detalladamente el siguiente punto: Se debe seleccionar primer el abono y luego seleccionar la recaudación hasta llegar al monto del abono y se realiza la conciliación.
¿Quién brindará los archivos excel? ¿De dónde se descargarán o se obtendrán estos archivos?
¿De dónde se obtienen los datos para completar la fecha y el número de conciliación?
