### ISSUE TITLE
P03_Relevamiento del Proceso_klopez

### ISSUE THREAD

**Issue by apandradech** [kmlopez/rpa-interseguros#93]
| Item  | Detalle |
| ------------- | ------------- |
| Descripción de la tarea  | Relevamiento de información con usuario sobre el proceso Suscripción de Degravamen  |
| Persona de Contacto  | PO = Juan Carlos Barros </br> KU = Jose Felix Mazzini Aranda|
| Notas  |  |
| Link relacionado (Box)  |  |
| Criterios de aceptación  | Se recibió la información sobre el proceso completo de los KU incluidos en el proceso |

Tarea general parte del proceso de desarrollo. Asociar las subtareas que correspondan.

**Comment by kmlopez** [comment]
Se coordina reunión con Juan Carlos Barros para presentación del Key User el lunes 5/Ago a las 9:30am y sería con quien se coordinaría las reuniónes de relevamiento.

**Comment by kmlopez** [comment]
05/Ago: Se coordina con Key User para 1era reunión el 06/Ago a las 9am

**Comment by kmlopez** [comment]
06/08: 1ra reunión de relevamiento con KU Jose Felix Mazzini Aranda. (9am)

**Comment by kmlopez** [comment]
07/08: Se pasa en On Hold, se priorizará Procesos 13 y 14.

**Comment by tanyaluna** [comment]
09/08: Se culminó el relevamiento del proceso
